### ISSUE TITLE
FieldControl #ReadOnly not working?

### ISSUE THREAD

**Issue by bkrencker** [SAP-samples/cloud-cap-hana-swapi#1]
Is it a bug that the FieldControl annotation is not working?
`![@Common.FieldControl] : #ReadOnly`

As a workaround you can define multiple services and set the entities to @readonly, as shown here with film-service, planet-service, starship-service etc.. 

What is your experience with the FieldControl annotation?

**Comment by jung-thomas** [comment]
I also could not get the FieldControl annotation to work in Fiori. Could be a bug. Ultimately though I felt the approach with @readonly at the entity level was a better option anyway. It enforced control not only at the UI level but within the service consumption as well.

**Comment by bkrencker** [comment]
Hi @jung-thomas 

Thanks for your response. I agree, for this example @readonly is indeed the better option. Although there might be a situation where FieldControl would be the better choice.

It seems that the FieldControl annotation has some problems: ![@Common.FieldControl] : #Mandatory is not working too..

Ben
