### ISSUE TITLE
If my star wars data is residing on a SAP SYSTEM

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAP-samples/cloud-cap-hana-swapi#3]
Hello experts,

If my some STAR WARS data is residing on a SAP S/4HANA System on which i have created an OData service V2, 
Like I have film entity data in my CAP model and other entities are residing on s/4 hana system, can i somehow consome them in my this CAP STAR WARS Application?

**Comment by jung-thomas** [comment]
There is nothing in this sample that covers such service mashup, but it is possible with CAP. I'd suggest you have a look at the CAP section from the TechEd 2021 Developer Keynote. This was the exact topic covered there.  https://github.com/SAP-samples/teched2021-developer-keynote/tree/main/section/cap

The only difference is that with on premise you'd need to use the SAP Cloud Connector in the setup of your Destination.

**Comment by ahmedkhan29789** [comment]
Thanks a lot Thomas you are the best, Many Many thanks and have a happy
Christmas 🎄 and New Year 😊😊
